# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GMT_pb2 as GMT__pb2


class TimeStampServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDocumentTimeStamp = channel.unary_unary(
                '/TimeStampService/GetDocumentTimeStamp',
                request_serializer=GMT__pb2.TimeStampRequest.SerializeToString,
                response_deserializer=GMT__pb2.TimeStampResponse.FromString,
                )


class TimeStampServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDocumentTimeStamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeStampServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDocumentTimeStamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentTimeStamp,
                    request_deserializer=GMT__pb2.TimeStampRequest.FromString,
                    response_serializer=GMT__pb2.TimeStampResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TimeStampService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeStampService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDocumentTimeStamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TimeStampService/GetDocumentTimeStamp',
            GMT__pb2.TimeStampRequest.SerializeToString,
            GMT__pb2.TimeStampResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
